spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/chaoshanbook?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ChaoShanBook
    password: ChaoShanBook=2019
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
  servlet:
    context-path: /chaoshanbook
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  # 配置mapper放置的位置，类路径下的mapper/下的所有Mapper.xml结尾的文件
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    # 处理枚举类型的handler
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload-file-path:
  video: /APP/upload/video
  picture: /APP/upload/picture

picture-base-url: http://111.231.245.190:8080/chaoshanbook/upload/picture/
video-base-url: http://111.231.245.190:8080/chaoshanbook/upload/video/

jwt-ttl-millis: 604800000